### PR TITLE
updates and cleanups

### PR DESCRIPTION
**Pull request by bomsy**
Notables

* Added `INIT` and `DESTROY` actions for initialise and cleanup
* Allow sending messages from the devtools-page to the CS
* Add functions to handle overlay manipulations
* getting the stacking context for the `body`

### CODE REVIEW

**Comment by bomsy** [comment]
@captainbrosset @gregtatum

**Review by gregtatum — APPROVED** [review]
I did a cursory review. All the changes look pretty reasonable.

**Comment by gregtatum** [comment]
Also thanks for keeping on pushing this through!

**Review by captainbrosset — COMMENTED** [review]
Looks great!
How about using the $0 API to show the stacking context tree below the currently selected  element?
This way the extension will be nicely tied to the inspector.

And if it returns false, then default to document.documentElement (instead of body), to show the whole tree.

If we do this though, we will also need a visual indication of the fact that only a subtree is being shown.

**Comment by bomsy** [comment]
@captainbrosset do you mean something like this ?
image

**Comment by bomsy** [comment]
Ahh ... i think i understand what you mean.

**Pull request merged**
