### PR TITLE
Improving responsiveness of display-rectangle

### PR DESCRIPTION
**Pull request by bkindersley**
not quite ready to merge in 

@gregtatum can you take a look at how i'm doing this? it feels kind of messy

i haven't managed to get the mutation observer working; can you clarify what 'mutations' exactly we want to pick up with it? is it supposed to supplement or replace the resize/scroll handlers?

### CODE REVIEW

**Comment by gregtatum** [comment]
I'll try and find some time tomorrow to look over the code, but in the meantime the mutation observer can observe the content in the page for when it changes. This would be a supplement to the existing resize handlers.

**Comment by bkindersley** [comment]
ready for review now.

**Comment by w-jiang** [comment]
1) On stacking-context-1, when I select div4, it doesn't highlight like the other blocks. I think this is because the highlight div display-rectangle is appearing beneath the actual div (this might be because the z-index of div4 is 2, but the z-index of the highlight is 1) (it also happens for some other examples like stacking-context)
2) src/components/app.js
DisplayRectangle isn't being used so just to keep things clean, we should remove line 13
3) src/components/display-rectangle.js
I might be being unnecessarily nitpicky but line 59 has an extra space... I use a package on Atom that automatically formats my code so maybe you'd find it useful too!

IT LOOKS FANTASTIC THOUGH! GOOD JOB :D

**Comment by w-jiang** [comment]
Thanks Bria! :)

**Pull request merged**
