### PR TITLE
WIP - Get Stacking Context info

### PR DESCRIPTION
**Pull request by bomsy**
WIP 

* Add background code to handle message passing between the panel and the content script
* Add content script to get the stacking context of the page.
* Make webpack environment aware etc

### CODE REVIEW

**Comment by bomsy** [comment]
@captainbrosset @gregtatum 

What we have now!

**Comment by captainbrosset** [comment]
Thanks @bomsy for the great work here.
I tested the extension quickly, and although some of it is still a bit hacky as we discussed, I believe we should land this.
It's a far superior development environment than before: there's a build step and commands to either run the code as a web app, or as a Firefox extension.
I am of the opinion that we should merge this now because this piece of work is foundational. Even if not all features currently work yet. We can iron out the details later in other PRs.
And the web app itself still works as before I think, so that part of the process is left untouched and other people can still contribute through there if needed.
@gregtatum what do you think? Ok to hit merge?

**Comment by bomsy** [comment]
Yeah .. the web app works as it was before , i tried not to touch

**Comment by gregtatum** [comment]
Sure I'm merging it in!

**Comment by bomsy** [comment]
@gregtatum thanks!

**Pull request merged**
